spring.application.name=api-management-service
server.port=8081

info.app.name=API Management Service
info.app.description=Custom API gateway for store, modify route and security policies

spring.datasource.url=jdbc:mysql://localhost:3306/gatekeeper_management
spring.datasource.username=root
spring.datasource.password=Mysql@250

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true